# Generated by Django 3.2 on 2021-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=100)),
                ('a_author', models.CharField(max_length=100)),
                ('a_narrator', models.CharField(max_length=100)),
                ('a_duration', models.FloatField()),
                ('a_uploaded_time', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_duation', models.FloatField()),
                ('p_uploaded_time', models.FloatField()),
                ('p_host', models.CharField(max_length=100)),
                ('p_participants', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_duation', models.FloatField()),
                ('s_uploaded_time', models.FloatField()),
            ],
        ),
    ]
