# Generated by Django 3.2 on 2021-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='a_duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='a_uploaded_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='p_duation',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='p_uploaded_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='s_duation',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='s_uploaded_time',
            field=models.TimeField(),
        ),
    ]
